importos
importhmac
importhashlib
importtime
importrequests
importjson
fromflaskimportFlask,request,jsonify
app=Flask(__name__)
DELTA_API_KEY=os.environ.get("DELTA_API_KEY")
DELTA_API_SECRET=os.environ.get("DELTA_API_SECRET")
BASE_URL=os.environ.get("DELTA_BASE_URL",
"https://api.india.delta.exch
ange")
defgenerate_signature(method,endpoint,payload_str,timestamp):
signature_data=method+timestamp+endpoint+payload_str
returnhmac.new(
DELTA_API_SECRET.encode('utf-8'),
signature_data.encode('utf-8'),
hashlib.sha256
).hexdigest()
defget_ticker_price(product_symbol):
try:
url=f"{BASE_URL}/v2/tickers/{product_symbol}"
response=requests.get(url)
data=response.json()
ifdata.get("success"):
returnfloat(data["result"]["close"])
exceptExceptionase:
print("Errorfetchingtickerprice:",str(e))
returnNone
defclose_existing_positions(product_symbol):
try:
endpoint="/v2/orders/close_all"
timestamp=str(int(time.time()))
payload={"product_symbol":product_symbol}
payload_str=json.dumps(payload)
signature=generate_signature("POST",endpoint,payload_str,
timestamp)
headers={
"api-key":DELTA_API_KEY,
"signature":signature,
"timestamp":timestamp,
"Content-Type":"application/json"
}
res=requests.post(BASE_URL+endpoint,data=payload_str,
headers=headers)
print("Closedpreviouspositions:",res.json())
time.sleep(1)
exceptExceptionase:
print("Errorclosingexistingpositions:",str(e))
defsend_delta_order(product_symbol,side,size):
c
lose_existing_positions(product_symbol)
endpoint="/v2/orders"
timestamp=str(int(time.time()))
current_price=get_ticker_price(product_symbol)
payload={
"product_symbol":product_symbol,
"size":int(size),
"side":side,
"order_type":"market_order"
}
ifcurrent_price:
ifside=="buy":
stop_loss_price=round(current_price*0.99,1)
take_profit_price=round(current_price*1.02,1)
e
lse:
stop_loss_price=round(current_price*1.01,1)
take_profit_price=round(current_price*0.98,1)
payload["stop_trigger_method"]="last_traded_price"
payload["bracket_stop_loss_price"]=str(stop_loss_price)
payload["bracket_take_profit_price"]=str(take_profit_price)
payload_str=json.dumps(payload)
signature=generate_signature("POST",endpoint,payload_str,
timestamp)
headers={
"api-key":DELTA_API_KEY,
"signature":signature,
"timestamp":timestamp,
"Content-Type":"application/json"
}
response=requests.post(BASE_URL+endpoint,
data=payload_str,headers=headers)
returnresponse.json()
@app.route('/',methods=['GET'])
defhealth_check():
return"DeltaBotisLive&Running!",200
@app.route('/webhook',methods=['POST'])
defwebhook():
try:
data=request.get_json()
ifnotdata:
returnjsonify({"status":"error","message":"NoJSONdata
received"}),400
symbol=data.get("symbol","BTCUSD")
action=data.get("action")
size=data.get("size",1)
ifactionin["buy","sell"]:
res=send_delta_order(symbol,action,size)
print("DeltaResponse:",res)
returnjsonify({"status":"success","delta_response":res}),200
e
lse:
returnjsonify({"status":"ignored","message":"Invalidaction"}),
400
exceptExceptionase:
print("Errorprocessingwebhook:",str(e))
returnjsonify({"status":"error","message":str(e)}),500
if__name__=='__main__':
app.run(host='0.0.0.0',port=5000)
